baseURL: "https://coreyst.one/"

title: coreyst.one/
paginate: 5
theme: PaperModX

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
pygmentsUseClasses: true

minify:
    disableXML: true
    minifyOutput: true

params:
    title: coreyst.one/
    description: ""
    keywords: [Blog, Portfolio]
    author: Me
    DateFormat: "January 2, 2006"
    defaultTheme: auto # dark, light
    disableThemeToggle: false

    ShowReadingTime: true
    ShowShareButtons: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: false
    disableSpecial1stPost: false
    disableScrollToTop: false
    comments: false
    hidemeta: false
    hideSummary: false
    showtoc: false
    tocopen: false

    assets:
        # disableFingerprinting: true
        favicon: favicon.ico
        apple_touch_icon: apple-touch-icon.png

    label:
        text: "Home"
        icon: /apple-touch-icon.png
        iconHeight: 35

    # profile-mode
    profileMode:
      enabled: true
      title: "🌊 👋 I'm Corey..." # optional default will be site title
      subtitle: |
        A dude passionate about digital privacy and helping people reclaim theirs.
        - Created [**Privacy Poodle**](https://github.com/coreystone), a tool that sends automated DSAR requests to data brokers
        - Created [**Privacy Policy Directory**](https://github.com/coreystone/privacy-policy-directory-data) & [**Web Scraper**](https://github.com/coreystone/privacypolicy_scraper), to help users easily find where to submit data requests; it also analyzes and highlights company privacy practices
      imageUrl: "/avatar.png"
      imageTitle: "" # optional
      imageWidth: 120 # custom size
      imageHeight: 120 # custom size
      buttons:
        - name: Contact
          url: "https://coreyst.one/contact/"

        - name: Resources
          url: "https://coreyst.one/resources/"

    # home-info mode
    homeInfoParams:
        Title: "Hi there \U0001F44B"
        Content: Welcome to my blog

    socialIcons:
      - name: github-simple
        url: "https://github.com/coreystone"
      - name: email
        url: "mailto:contact@coreyst.one"
      - name: linkedin-simple
        url: "https://linkedin.com/in/coreyjs"


menu:
  main:

    - name: Contact
      url: /contact/
      weight: 1
    - name: Resources
      url: /resources/
      weight: 2