baseURL: "https://coreyst.one"
title: Corey Stone
paginate: 5
theme: PaperModX

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
pygmentsUseClasses: true

minify:
    disableXML: true
    #minifyOutput: true

params:
    author: Me
    DateFormat: "January 2, 2006"
    defaultTheme: auto # dark, light
    disableThemeToggle: false
    TocSide: 'right'

    ShowReadingTime: true
    ShowShareButtons: false
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    disableSpecial1stPost: false
    disableScrollToTop: false
    comments: false
    hidemeta: false
    hideSummary: false
    showtoc: false
    tocopen: false

    assets:
        # disableFingerprinting: true
        #favicon16x16: "/favicon-16.png"
        #favicon32x32: "/favicon-32.png"
        #apple_touch_icon: "/apple-touch-icon.png"

    label:
        #text: "Home"
        #icon: /apple-touch-icon.png
        #iconHeight: 35

    # home-info mode
    homeInfoParams:
        Title: "Welcome! \U0001F44B"
        Content: |
          ## {{< figure align=center src="/images/sup.png" >}}
          ## *I'm* [*Corey*](https://coreyst.one/about/).

          - I'm passionate about digital privacy and believe that protecting personal information is not only a right,
            but a crucial part of the fight to defend our freedoms and autonomy in the digital age.
            **Privacy** enables us to exercise our rights and make informed choices
            while living without fear of surveillance or manipulation by corporations or governments; it is a [foundation of democracy](https://www.ned.org/big-question-how-does-digital-privacy-matter-for-democracy-and-its-advocates/).
            And it can be fun.

          - I like to write about privacy and digital security; you can read below or by clicking [**here**](https://coreyst.one/posts/).
          - You can see some of my other work by clicking on [**Projects**](https://coreyst.one/projects/).
          - Contact me via any of the methods below, or see [**About Me**](https://coreyst.one/about/#how-to-contact-me).

    socialIcons:
        - name: github-simple
          url: "https://github.com/coreystone"
        - name: linkedin-simple
          url: "https://linkedin.com/in/coreyjs"
        - name: pgpkey
          url: "https://coreyst.one/about/#pgp-key"

    cover:
        hidden: true # hide everywhere but not in structured data
        hiddenInList: true # hide on list pages and home
        hiddenInSingle: true # hide on single page

menu:
    main:
        - identifier: about me
          name: About Me
          url: /about/
          weight: 10
        - identifier: blog
          name: Blog
          url: /posts/
          weight: 20
        - identifier: projects
          name: Projects
          url: /projects/
          weight: 30